export const SET_CHARACTERS = 'SET_CHARACTERS';
export const SET_ACTIVE_CHARACTER = 'SET_ACTIVE_CHARACTER';
export const SET_EPISODES = 'SET_EPISODES';
export const SET_LOCATIONS = 'SET_LOCATIONS';
export const SET_WATCHLIST = 'SET_WATCHLIST';
export const ADD_WATCHITEM = 'ADD_WATCHITEM';
export const DELETE_WATCHITEM = 'DELETE_WATCHITEM';
export const TOGGLE_COMPLETE = 'TOGGLE_COMPLETE';
